[package]
name = "example"
version = "0.1.0"
authors = ["Roman Zubov <romazu@protonmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
ethereum-types = "0.14"
rustsol = { path = "../rustsol" }

[[bin]]
name = "generate"
path = "src/generate.rs"

[[bin]]
name = "run"
path = "src/run.rs"